# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'TestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp
pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

  target 'TestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp-tvOS

  target 'TestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
